OMDb_Scrabber/Controllers/ImdbController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;
using Saritasa.Tools.Messages.Abstractions;
using System.Threading.Tasks;
using OMDbScrabberLibrary.MoviesContext;

namespace OMDbScrabber.Controllers
{
    /// <summary>
    /// MVC Controller.
    /// </summary>
    public class ImdbController : Controller
    {
        private readonly IMessagePipelineService pipelineService;

        /// <summary>
        /// Constructor with arguments.
        /// </summary>
        public ImdbController(IMessagePipelineService pipelineService)
        {
            this.pipelineService = pipelineService ?? throw new ArgumentNullException(nameof(pipelineService));
        }

        /// <summary>
        /// First page displayed entry and button.
        /// </summary>
        public IActionResult Upload()
        {
            return View();
        }

        /// <summary>
        /// Second page displaed sorted movies.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> List(decimal ratingAbove = 0, int runtimeMinsAbove = 0, int runtimeMinsBelow = 0, string hasActor = "")
        {
            ViewBag.RatingAbove = ratingAbove;
            ViewBag.RuntimeMinsAbove = runtimeMinsAbove;
            ViewBag.RuntimeMinsBelow = runtimeMinsBelow;
            ViewBag.HasActor = hasActor;

            ViewBag.Movies = pipelineService.Query<ImdbQueries>().With(q => q.Search(ratingAbove, runtimeMinsAbove, runtimeMinsBelow, hasActor));
            return View();
        }

        /// <summary>
        /// Second page displayed unsorted movies.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> List(string ids)
        {
            var command = new ImportImdbMoviesInfoCommand()
            {
                ImdbIds = ids.Split(',').Select(i => i.Trim()).ToArray()
            };
            await pipelineService.HandleCommandAsync(command);
            return Redirect("List");
        }
    }
}

OMDb_Scrabber/Pages/Shared/List.cshtml
@using OMDbScrabberLibrary.Entities;
@using OMDbScrabberLibrary.Dtos;
<h3>Movies in your library:</h3>
<table>
    <tr>
        <th>ImdbId</th>
        <th>Title</th>
        <th>Year</th>
        <th>Runtime Mins</th>
        <th>Genre</th>
        <th>Actors</th>
        <th>Rating</th>

    </tr>
    <tbody>
        @foreach (var movieActors in (ViewBag.Movies as List<MovieActorsDto>))
        {
        <tr>
            <td>@movieActors.Movie.ImdbId</td>
            <td><b>@movieActors.Movie.Title</b></td>
            <td>@movieActors.Movie.ReleaseDate.ToString("yyyy")</td>
            <td>@movieActors.Movie.RuntimeMins</td>
            <td>@movieActors.Movie.Genre</td>
            <td>@String.Join(", ", movieActors.Actors.Select(a => a.Name).ToArray())</td>
            <td>@movieActors.Movie.ImdbRating</td>
        </tr>
        }
    </tbody>
</table>

<h3>Filter your library:</h3>
@using (Html.BeginForm("List", "Imdb", FormMethod.Get))
{
    <table>
        <tr>
            <td><p>Rating Above: </p></td>
            <td><input type="text" name="ratingAbove" value="@ViewBag.RatingAbove" /> </td>
        </tr>
        <tr>
            <td><p>Runtime Mins Above: </p></td>
            <td><input type="number" name="runtimeMinsAbove" value="@ViewBag.RuntimeMinsAbove" /> </td>
        </tr>
        <tr>
            <td><p>Runtime Mins Below: </p></td>
            <td><input type="number" name="runtimeMinsBelow" value="@ViewBag.RuntimeMinsBelow" /> </td>
        </tr>
        <tr>
            <td><p>Has Actor: </p></td>
            <td><input type="text" name="hasActor" value="@ViewBag.HasActor"/> </td>
        </tr>

        <tr>
            <td><input type="submit" value="Filter" /> </td>
            <td></td>
        </tr>
    </table>

}

OMDb_Scrabber/Pages/Shared/Upload.cshtml
@using (Html.BeginForm("List", "Imdb", FormMethod.Post))
{

    <table>
        <tr>
            <td><p>Enter Ids: </p></td>
            <td><textarea name="ids"></textarea></td>
        </tr>

        <tr>
            <td><input type="submit" value="Get movies!" /> </td>
            <td></td>
        </tr>
    </table>

}